[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.2.1",
    "gtts>=2.5.4",
    "librosa>=0.11.0",
    "matplotlib>=3.11.0",
    "numba>=0.61",
    "numpy>=2.4.6",
    "rapidfuzz>=3.14.5",
    "soundfile>=0.14.0",
    "tqdm>=4.68.3",
]
