[env:heltec_wifi_lora_32_V3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    https://github.com/ropg/heltec_esp32_lora_v3.git
    jgromes/RadioLib@^6.6.0
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
